sudo: required
language: go
go: 1.8
services:
    - docker

install:
    - sudo apt-get install -y pandoc

after_success:
    - bash <(curl -s https://codecov.io/bash)

deploy:
    - provider: script
      script: make push
      on:
          branch: master
